import { alpha, mix } from "./color.js";
import { roles } from "./syntax.js";

/** @typedef {import("./palettes.js").Palette} Palette */
/** @typedef {import("./accents.js").Accent} Accent */

/**
 * Workbench colors, grouped as in the theme color reference. Unset keys keep VS
 * Code defaults, derived from the ones set here.
 *
 * @param {Palette} p
 * @param {Accent} a
 * @returns {Record<string, string>}
 */
export function workbench(p, a) {
  const { bg, fg, ink, fill } = p;
  const dark = p.type === "dark";
  const r = roles(p);

  // Overlays stay neutral by tinting with the foreground; `dark` scales them to equal perceived weight.
  const shade = (opacity) => alpha(fg.default, dark ? opacity : opacity * 0.8);
  const shadow = alpha("#000000", dark ? 0.5 : 0.16);
  const widget = dark ? bg.chrome : bg.editor;
  const selection = alpha(fill.blue, dark ? 0.6 : 0.2);
  const hover = (color) => mix(color, fg.default, 0.12);
  const status = {
    error: ink.red,
    warning: ink.yellow,
    info: ink.blue,
    hint: ink.cyan,
    success: ink.green,
  };

  return {
    // Base
    focusBorder: a.focus,
    foreground: fg.default,
    disabledForeground: alpha(fg.muted, 0.6),
    descriptionForeground: fg.muted,
    errorForeground: status.error,
    "icon.foreground": fg.muted,
    "widget.border": bg.line,
    "widget.shadow": shadow,
    "selection.background": selection,
    "sash.hoverBorder": a.focus,

    // Modern UI
    "surface.background": widget,
    "surface.foreground": fg.default,
    "surface.border": bg.line,
    "editor.border": bg.line,
    "modernPanel.border": bg.line,
    "modernUI.shellBackground": bg.chrome,
    "modernUI.inactiveShellBackground": bg.chrome,
    "modernActivityBar.background": bg.chrome,
    "modernActivityBarItem.activeBackground": a.active.activity.background,
    "modernActivityBarItem.activeForeground": a.active.activity.foreground,
    "modernActivityBarItem.hoverBackground": shade(0.08),
    "modernActivityBarItem.hoverForeground": fg.default,
    "modernTab.activeBackground": a.active.panel.background,
    "modernTab.activeForeground": a.active.panel.foreground,
    "modernTab.hoverBackground": shade(0.08),
    "modernTab.hoverForeground": fg.default,
    "modernEditorTab.activeBackground": bg.editor,
    "modernEditorTab.activeForeground": fg.default,
    "modernEditorTab.inactiveBackground": bg.chrome,
    "modernEditorTab.hoverBackground": shade(0.05),
    "modernEditorTab.hoverForeground": fg.default,

    // Text
    "textLink.foreground": a.focus,
    "textLink.activeForeground": a.focus,
    "textBlockQuote.background": bg.chrome,
    "textBlockQuote.border": a.focus,
    "textCodeBlock.background": shade(0.06),
    "textPreformat.foreground": r.type,
    "textPreformat.background": shade(0.08),
    "textSeparator.foreground": bg.line,

    // Actions, toolbar
    "toolbar.hoverBackground": shade(0.1),
    "toolbar.activeBackground": shade(0.16),
    "actionBar.toggledBackground": alpha(a.focus, 0.25),

    // Button, checkbox, dropdown, input
    "button.background": a.button.background,
    "button.foreground": a.button.foreground,
    "button.hoverBackground": hover(a.button.background),
    "button.secondaryBackground": bg.line,
    "button.secondaryForeground": fg.default,
    "button.secondaryHoverBackground": hover(bg.line),
    "checkbox.background": bg.editor,
    "checkbox.foreground": fg.default,
    "checkbox.border": bg.line,
    "dropdown.background": widget,
    "dropdown.listBackground": widget,
    "dropdown.foreground": fg.default,
    "dropdown.border": bg.line,
    "input.background": bg.editor,
    "input.foreground": fg.default,
    "input.border": bg.line,
    "input.placeholderForeground": fg.muted,
    "inputOption.activeBackground": alpha(a.focus, 0.25),
    "inputOption.activeBorder": a.focus,
    "inputOption.activeForeground": fg.default,
    "inputValidation.errorBackground": widget,
    "inputValidation.errorBorder": status.error,
    "inputValidation.warningBackground": widget,
    "inputValidation.warningBorder": status.warning,
    "inputValidation.infoBackground": widget,
    "inputValidation.infoBorder": status.info,

    // Scrollbar
    "scrollbar.shadow": shadow,
    "scrollbarSlider.background": shade(0.12),
    "scrollbarSlider.hoverBackground": shade(0.2),
    "scrollbarSlider.activeBackground": shade(0.3),

    // Badge, progress
    "badge.background": bg.line,
    "badge.foreground": fg.default,
    "progressBar.background": a.focus,

    // Lists and trees
    "list.activeSelectionBackground": bg.line,
    "list.activeSelectionForeground": fg.default,
    "list.activeSelectionIconForeground": fg.default,
    "list.inactiveSelectionBackground": shade(0.08),
    "list.inactiveSelectionForeground": fg.default,
    "list.hoverBackground": shade(0.05),
    "list.hoverForeground": fg.default,
    "list.focusOutline": a.focus,
    "list.highlightForeground": a.focus,
    "list.focusHighlightForeground": a.focus,
    "list.errorForeground": status.error,
    "list.warningForeground": status.warning,
    "list.invalidItemForeground": status.error,
    "list.deemphasizedForeground": fg.muted,
    "list.dropBackground": alpha(a.focus, 0.15),
    "listFilterWidget.background": widget,
    "listFilterWidget.outline": a.focus,
    "listFilterWidget.noMatchesOutline": status.error,
    "tree.indentGuidesStroke": bg.line,
    "tree.inactiveIndentGuidesStroke": alpha(bg.line, 0.5),

    // Activity bar
    "activityBar.background": bg.chrome,
    "activityBar.foreground": fg.default,
    "activityBar.inactiveForeground": fg.muted,
    "activityBar.border": bg.line,
    "activityBar.activeBorder": a.active.activity.background,
    "activityBarBadge.background": a.badge.background,
    "activityBarBadge.foreground": a.badge.foreground,
    "activityBarTop.foreground": fg.default,
    "activityBarTop.inactiveForeground": fg.muted,
    "activityBarTop.activeBorder": a.active.activity.background,
    "activityErrorBadge.background": fill.red,
    "activityErrorBadge.foreground": p.onFill.red,
    "activityWarningBadge.background": fill.yellow,
    "activityWarningBadge.foreground": p.onFill.yellow,
    "profileBadge.background": bg.line,
    "profileBadge.foreground": fg.default,

    // Side bar
    "sideBar.background": bg.chrome,
    "sideBar.foreground": fg.muted,
    "sideBar.border": bg.line,
    "sideBar.dropBackground": alpha(a.focus, 0.15),
    "sideBarTitle.foreground": fg.default,
    "sideBarSectionHeader.background": bg.chrome,
    "sideBarSectionHeader.foreground": fg.default,
    "sideBarSectionHeader.border": bg.line,
    "sideBarActivityBarTop.border": bg.line,

    // Minimap
    "minimap.background": bg.editor,
    "minimap.selectionHighlight": selection,
    "minimap.findMatchHighlight": ink.yellow,
    "minimap.errorHighlight": status.error,
    "minimap.warningHighlight": status.warning,
    "minimapSlider.background": shade(0.08),
    "minimapSlider.hoverBackground": shade(0.12),
    "minimapSlider.activeBackground": shade(0.16),
    "minimapGutter.addedBackground": ink.green,
    "minimapGutter.modifiedBackground": ink.yellow,
    "minimapGutter.deletedBackground": ink.red,

    // Editor groups and tabs
    "editorGroup.border": bg.line,
    "editorGroup.dropBackground": alpha(a.focus, 0.12),
    "editorGroupHeader.tabsBackground": bg.chrome,
    "editorGroupHeader.tabsBorder": bg.line,
    "editorGroupHeader.noTabsBackground": bg.editor,
    "tab.activeBackground": bg.editor,
    "tab.activeForeground": fg.default,
    "tab.activeBorderTop": a.active.tab,
    "tab.activeModifiedBorder": a.active.tab,
    "tab.inactiveBackground": bg.chrome,
    "tab.inactiveForeground": fg.muted,
    "tab.inactiveModifiedBorder": alpha(a.active.tab, 0.5),
    "tab.hoverBackground": shade(0.05),
    "tab.border": bg.line,
    "tab.lastPinnedBorder": bg.line,
    "tab.dragAndDropBorder": a.focus,
    "tab.unfocusedActiveBorderTop": alpha(a.active.tab, 0.5),
    "tab.unfocusedActiveForeground": fg.muted,
    "tab.unfocusedInactiveForeground": fg.muted,
    "tab.unfocusedActiveModifiedBorder": alpha(a.active.tab, 0.5),

    // Editor
    "editor.background": bg.editor,
    "editor.foreground": fg.default,
    "editorLineNumber.foreground": fg.muted,
    "editorLineNumber.activeForeground": fg.default,
    "editorLineNumber.dimmedForeground": alpha(fg.muted, 0.5),
    "editorCursor.foreground": a.focus,
    "editorCursor.background": bg.editor,
    "editor.selectionBackground": selection,
    "editor.inactiveSelectionBackground": alpha(fill.blue, dark ? 0.3 : 0.1),
    "editor.selectionHighlightBackground": alpha(fill.blue, dark ? 0.35 : 0.12),
    "editor.selectionHighlightBorder": alpha(ink.blue, 0.5),
    "editor.wordHighlightBackground": shade(0.08),
    "editor.wordHighlightStrongBackground": shade(0.14),
    "editor.wordHighlightTextBackground": shade(0.06),
    "editor.findMatchBackground": alpha(fill.yellow, 0.4),
    "editor.findMatchBorder": ink.yellow,
    "editor.findMatchHighlightBackground": alpha(fill.yellow, 0.2),
    "editor.findMatchHighlightBorder": alpha(ink.yellow, 0.5),
    "editor.findRangeHighlightBackground": shade(0.05),
    "editor.hoverHighlightBackground": alpha(fill.blue, 0.25),
    "editor.lineHighlightBackground": shade(0.04),
    "editor.lineHighlightBorder": alpha(fg.default, 0),
    "editor.rangeHighlightBackground": shade(0.05),
    "editor.symbolHighlightBackground": alpha(fill.yellow, 0.2),
    "editor.foldBackground": alpha(fill.blue, 0.15),
    "editor.linkedEditingBackground": alpha(fill.blue, 0.2),
    "editor.placeholder.foreground": fg.muted,
    "editorLink.activeForeground": a.focus,
    "editorWhitespace.foreground": alpha(fg.muted, 0.4),
    "editorIndentGuide.background1": bg.line,
    "editorIndentGuide.activeBackground1": fg.muted,
    "editorRuler.foreground": bg.line,
    "editorCodeLens.foreground": fg.muted,
    "editorInlayHint.foreground": fg.muted,
    "editorInlayHint.background": shade(0.06),
    "editorGhostText.foreground": fg.muted,
    "editorBracketMatch.background": alpha(fill.blue, 0.3),
    "editorBracketMatch.border": fg.muted,
    "editorBracketHighlight.foreground1": ink.yellow,
    "editorBracketHighlight.foreground2": ink.violet,
    "editorBracketHighlight.foreground3": ink.blue,
    "editorBracketHighlight.foreground4": ink.orange,
    "editorBracketHighlight.foreground5": ink.cyan,
    "editorBracketHighlight.foreground6": ink.green,
    "editorBracketHighlight.unexpectedBracket.foreground": status.error,
    "editorError.foreground": status.error,
    "editorWarning.foreground": status.warning,
    "editorInfo.foreground": status.info,
    "editorHint.foreground": status.hint,
    "editorLightBulb.foreground": ink.yellow,
    "editorLightBulbAutoFix.foreground": ink.blue,
    "editorUnnecessaryCode.opacity": alpha("#000000", 0.6),
    "editorGutter.background": bg.editor,
    "editorGutter.addedBackground": ink.green,
    "editorGutter.modifiedBackground": ink.yellow,
    "editorGutter.deletedBackground": ink.red,
    "editorGutter.foldingControlForeground": fg.muted,
    "editorOverviewRuler.border": alpha(fg.default, 0),
    "editorOverviewRuler.errorForeground": status.error,
    "editorOverviewRuler.warningForeground": status.warning,
    "editorOverviewRuler.infoForeground": status.info,
    "editorOverviewRuler.addedForeground": alpha(ink.green, 0.6),
    "editorOverviewRuler.modifiedForeground": alpha(ink.yellow, 0.6),
    "editorOverviewRuler.deletedForeground": alpha(ink.red, 0.6),
    "editorOverviewRuler.findMatchForeground": alpha(ink.yellow, 0.6),
    "editorOverviewRuler.selectionHighlightForeground": alpha(ink.blue, 0.5),
    "editorOverviewRuler.bracketMatchForeground": fg.muted,
    "editorStickyScroll.background": bg.editor,
    "editorStickyScroll.shadow": shadow,
    "editorStickyScrollHover.background": shade(0.06),
    "editorMultiCursor.primary.foreground": a.focus,
    "editorMultiCursor.secondary.foreground": alpha(a.focus, 0.6),

    // Diff editor
    "diffEditor.insertedTextBackground": alpha(fill.green, dark ? 0.35 : 0.2),
    "diffEditor.insertedLineBackground": alpha(fill.green, dark ? 0.2 : 0.1),
    "diffEditor.removedTextBackground": alpha(fill.red, dark ? 0.35 : 0.2),
    "diffEditor.removedLineBackground": alpha(fill.red, dark ? 0.2 : 0.1),
    "diffEditor.diagonalFill": bg.line,
    "diffEditor.border": bg.line,

    // Chat
    "chat.requestBorder": bg.line,
    "chat.requestBackground": shade(0.04),
    "chat.slashCommandBackground": alpha(a.focus, 0.2),
    "chat.slashCommandForeground": fg.default,
    "chat.avatarBackground": bg.line,
    "chat.avatarForeground": fg.default,
    "chat.editedFileForeground": ink.yellow,
    "chat.linesAddedForeground": ink.green,
    "chat.linesRemovedForeground": ink.red,
    "inlineChat.background": widget,
    "inlineChat.foreground": fg.default,
    "inlineChat.border": bg.line,
    "inlineChatInput.background": bg.editor,
    "inlineChatInput.border": bg.line,
    "inlineChatInput.focusBorder": a.focus,
    "inlineChatInput.placeholderForeground": fg.muted,
    "inlineChatDiff.inserted": alpha(fill.green, 0.2),
    "inlineChatDiff.removed": alpha(fill.red, 0.2),

    // Editor widgets
    "editorWidget.background": widget,
    "editorWidget.foreground": fg.default,
    "editorWidget.border": bg.line,
    "editorWidget.resizeBorder": a.focus,
    "editorSuggestWidget.background": widget,
    "editorSuggestWidget.foreground": fg.default,
    "editorSuggestWidget.border": bg.line,
    "editorSuggestWidget.highlightForeground": a.focus,
    "editorSuggestWidget.focusHighlightForeground": a.focus,
    "editorSuggestWidget.selectedBackground": bg.line,
    "editorSuggestWidget.selectedForeground": fg.default,
    "editorSuggestWidget.selectedIconForeground": fg.default,
    "editorHoverWidget.background": widget,
    "editorHoverWidget.foreground": fg.default,
    "editorHoverWidget.border": bg.line,
    "editorHoverWidget.highlightForeground": a.focus,
    "editorHoverWidget.statusBarBackground": bg.chrome,
    "editorActionList.background": widget,
    "editorActionList.foreground": fg.default,
    "editorActionList.focusBackground": bg.line,
    "editorActionList.focusForeground": fg.default,
    "debugExceptionWidget.background": widget,
    "debugExceptionWidget.border": status.error,

    // Peek view
    "peekView.border": a.focus,
    "peekViewEditor.background": bg.chrome,
    "peekViewEditorGutter.background": bg.chrome,
    "peekViewEditor.matchHighlightBackground": alpha(fill.yellow, 0.35),
    "peekViewResult.background": bg.chrome,
    "peekViewResult.fileForeground": fg.default,
    "peekViewResult.lineForeground": fg.muted,
    "peekViewResult.matchHighlightBackground": alpha(fill.yellow, 0.35),
    "peekViewResult.selectionBackground": bg.line,
    "peekViewResult.selectionForeground": fg.default,
    "peekViewTitle.background": bg.chrome,
    "peekViewTitleLabel.foreground": fg.default,
    "peekViewTitleDescription.foreground": fg.muted,

    // Merge conflicts
    "merge.border": bg.line,
    "merge.currentHeaderBackground": alpha(fill.green, 0.5),
    "merge.currentContentBackground": alpha(fill.green, 0.2),
    "merge.incomingHeaderBackground": alpha(fill.blue, 0.5),
    "merge.incomingContentBackground": alpha(fill.blue, 0.2),
    "merge.commonHeaderBackground": alpha(fg.muted, 0.4),
    "merge.commonContentBackground": alpha(fg.muted, 0.15),
    "editorOverviewRuler.currentContentForeground": alpha(ink.green, 0.6),
    "editorOverviewRuler.incomingContentForeground": alpha(ink.blue, 0.6),
    "editorOverviewRuler.commonContentForeground": alpha(fg.muted, 0.6),

    // Panel
    "panel.background": bg.chrome,
    "panel.border": bg.line,
    "panelTitle.activeBorder": a.active.panel.background,
    "panelTitle.activeForeground": fg.default,
    "panelTitle.inactiveForeground": fg.muted,
    "panelInput.border": bg.line,
    "panelSection.border": bg.line,
    "panelSectionHeader.background": bg.chrome,

    // Status bar
    "statusBar.background": a.statusBar.background,
    "statusBar.foreground": a.statusBar.foreground,
    "statusBar.border":
      a.statusBar.background === bg.chrome ? bg.line : a.statusBar.background,
    "statusBar.debuggingBackground": a.debugging.background,
    "statusBar.debuggingForeground": a.debugging.foreground,
    "statusBar.debuggingBorder": a.debugging.background,
    "statusBar.noFolderBackground": a.noFolder.background,
    "statusBar.noFolderForeground": a.noFolder.foreground,
    "statusBarItem.remoteBackground": a.remote.background,
    "statusBarItem.remoteForeground": a.remote.foreground,
    "statusBarItem.remoteHoverBackground": hover(a.remote.background),
    "statusBarItem.hoverBackground": alpha(a.statusBar.foreground, 0.12),
    "statusBarItem.activeBackground": alpha(a.statusBar.foreground, 0.2),
    "statusBarItem.prominentBackground": alpha(a.statusBar.foreground, 0.15),
    "statusBarItem.errorBackground": fill.red,
    "statusBarItem.errorForeground": p.onFill.red,
    "statusBarItem.warningBackground": fill.yellow,
    "statusBarItem.warningForeground": p.onFill.yellow,

    // Title bar, menu, command center
    "titleBar.activeBackground": bg.chrome,
    "titleBar.activeForeground": fg.default,
    "titleBar.inactiveBackground": bg.chrome,
    "titleBar.inactiveForeground": fg.muted,
    "titleBar.border": bg.line,
    "menu.background": widget,
    "menu.foreground": fg.default,
    "menu.border": bg.line,
    "menu.selectionBackground": bg.line,
    "menu.selectionForeground": fg.default,
    "menu.separatorBackground": bg.line,
    "menubar.selectionBackground": shade(0.1),
    "commandCenter.background": shade(0.05),
    "commandCenter.foreground": fg.muted,
    "commandCenter.activeBackground": shade(0.1),
    "commandCenter.activeForeground": fg.default,
    "commandCenter.border": bg.line,

    // Notifications, banner
    "notifications.background": widget,
    "notifications.foreground": fg.default,
    "notifications.border": bg.line,
    "notificationCenter.border": bg.line,
    "notificationCenterHeader.background": bg.chrome,
    "notificationToast.border": bg.line,
    "notificationLink.foreground": a.focus,
    "notificationsErrorIcon.foreground": status.error,
    "notificationsWarningIcon.foreground": status.warning,
    "notificationsInfoIcon.foreground": status.info,
    "banner.background": bg.line,
    "banner.foreground": fg.default,
    "banner.iconForeground": a.focus,

    // Extensions
    "extensionButton.prominentBackground": a.button.background,
    "extensionButton.prominentForeground": a.button.foreground,
    "extensionButton.prominentHoverBackground": hover(a.button.background),
    "extensionBadge.remoteBackground": a.badge.background,
    "extensionBadge.remoteForeground": a.badge.foreground,
    "extensionIcon.starForeground": ink.yellow,
    "extensionIcon.verifiedForeground": ink.blue,

    // Quick picker, keybindings
    "quickInput.background": widget,
    "quickInput.foreground": fg.default,
    "quickInputTitle.background": bg.chrome,
    "quickInputList.focusBackground": bg.line,
    "quickInputList.focusForeground": fg.default,
    "quickInputList.focusIconForeground": fg.default,
    "pickerGroup.border": bg.line,
    "pickerGroup.foreground": a.focus,
    "keybindingLabel.background": shade(0.08),
    "keybindingLabel.foreground": fg.default,
    "keybindingLabel.border": bg.line,
    "keybindingLabel.bottomBorder": bg.line,
    "keybindingTable.rowsBackground": shade(0.03),

    // Terminal
    "terminal.background": bg.chrome,
    "terminal.foreground": fg.default,
    "terminal.border": bg.line,
    "terminal.selectionBackground": selection,
    "terminal.findMatchBackground": alpha(fill.yellow, 0.4),
    "terminal.findMatchHighlightBackground": alpha(fill.yellow, 0.2),
    "terminal.tab.activeBorder": a.active.panel.background,
    "terminalCursor.foreground": a.focus,
    "terminalCommandDecoration.defaultBackground": fg.muted,
    "terminalCommandDecoration.successBackground": status.success,
    "terminalCommandDecoration.errorBackground": status.error,
    "terminal.ansiBlack": dark ? bg.line : fg.default,
    "terminal.ansiRed": ink.red,
    "terminal.ansiGreen": ink.green,
    "terminal.ansiYellow": ink.yellow,
    "terminal.ansiBlue": ink.blue,
    "terminal.ansiMagenta": ink.violet,
    "terminal.ansiCyan": ink.cyan,
    "terminal.ansiWhite": dark ? fg.muted : bg.line,
    "terminal.ansiBrightBlack": fg.muted,
    "terminal.ansiBrightRed": p.bright.red,
    "terminal.ansiBrightGreen": p.bright.green,
    "terminal.ansiBrightYellow": p.bright.yellow,
    "terminal.ansiBrightBlue": p.bright.blue,
    "terminal.ansiBrightMagenta": p.bright.violet,
    "terminal.ansiBrightCyan": p.bright.cyan,
    "terminal.ansiBrightWhite": dark ? fg.default : bg.editor,

    // Debug
    "debugToolBar.background": widget,
    "debugToolBar.border": bg.line,
    "editor.stackFrameHighlightBackground": alpha(fill.yellow, 0.2),
    "editor.focusedStackFrameHighlightBackground": alpha(fill.green, 0.25),
    "debugIcon.breakpointForeground": ink.red,
    "debugIcon.breakpointDisabledForeground": fg.muted,
    "debugIcon.breakpointUnverifiedForeground": fg.muted,
    "debugIcon.breakpointCurrentStackframeForeground": ink.yellow,
    "debugIcon.breakpointStackframeForeground": ink.green,
    "debugIcon.startForeground": ink.green,
    "debugConsole.errorForeground": status.error,
    "debugConsole.warningForeground": status.warning,
    "debugConsole.infoForeground": status.info,
    "debugConsole.sourceForeground": fg.muted,
    "debugTokenExpression.name": r.variable,
    "debugTokenExpression.value": fg.default,
    "debugTokenExpression.string": r.string,
    "debugTokenExpression.number": r.constant,
    "debugTokenExpression.boolean": r.constant,
    "debugTokenExpression.type": r.type,
    "debugTokenExpression.error": status.error,

    // Testing
    "testing.iconPassed": status.success,
    "testing.iconFailed": status.error,
    "testing.iconErrored": status.error,
    "testing.iconQueued": status.warning,
    "testing.iconSkipped": fg.muted,
    "testing.iconUnset": fg.muted,
    "testing.runAction": status.success,

    // Git, SCM graph
    "gitDecoration.addedResourceForeground": ink.green,
    "gitDecoration.untrackedResourceForeground": ink.green,
    "gitDecoration.modifiedResourceForeground": ink.yellow,
    "gitDecoration.stageModifiedResourceForeground": ink.yellow,
    "gitDecoration.deletedResourceForeground": ink.red,
    "gitDecoration.stageDeletedResourceForeground": ink.red,
    "gitDecoration.renamedResourceForeground": ink.cyan,
    "gitDecoration.conflictingResourceForeground": ink.violet,
    "gitDecoration.submoduleResourceForeground": ink.blue,
    "gitDecoration.ignoredResourceForeground": alpha(fg.muted, 0.7),
    "scmGraph.foreground1": ink.red,
    "scmGraph.foreground2": ink.yellow,
    "scmGraph.foreground3": ink.blue,
    "scmGraph.foreground4": ink.green,
    "scmGraph.foreground5": ink.violet,
    "scmGraph.historyItemRefColor": ink.blue,
    "scmGraph.historyItemRemoteRefColor": ink.violet,
    "scmGraph.historyItemBaseRefColor": ink.orange,

    // Settings, breadcrumbs, snippets
    "settings.headerForeground": fg.default,
    "settings.headerBorder": bg.line,
    "settings.modifiedItemIndicator": a.focus,
    "settings.focusedRowBackground": shade(0.04),
    "settings.focusedRowBorder": a.focus,
    "settings.rowHoverBackground": shade(0.03),
    "breadcrumb.background": bg.editor,
    "breadcrumb.foreground": fg.muted,
    "breadcrumb.focusForeground": fg.default,
    "breadcrumb.activeSelectionForeground": fg.default,
    "breadcrumbPicker.background": widget,
    "editor.snippetTabstopHighlightBackground": alpha(fill.blue, 0.3),
    "editor.snippetFinalTabstopHighlightBorder": ink.green,

    // Symbol icons follow syntax roles
    "symbolIcon.arrayForeground": r.operator,
    "symbolIcon.booleanForeground": r.constant,
    "symbolIcon.classForeground": r.type,
    "symbolIcon.colorForeground": r.text,
    "symbolIcon.constantForeground": r.constant,
    "symbolIcon.constructorForeground": r.function,
    "symbolIcon.enumeratorForeground": r.type,
    "symbolIcon.enumeratorMemberForeground": r.constant,
    "symbolIcon.eventForeground": r.variable,
    "symbolIcon.fieldForeground": r.text,
    "symbolIcon.fileForeground": r.text,
    "symbolIcon.folderForeground": fg.muted,
    "symbolIcon.functionForeground": r.function,
    "symbolIcon.interfaceForeground": r.type,
    "symbolIcon.keyForeground": r.keyword,
    "symbolIcon.keywordForeground": r.keyword,
    "symbolIcon.methodForeground": r.function,
    "symbolIcon.moduleForeground": r.type,
    "symbolIcon.namespaceForeground": r.type,
    "symbolIcon.nullForeground": r.constant,
    "symbolIcon.numberForeground": r.constant,
    "symbolIcon.objectForeground": r.type,
    "symbolIcon.operatorForeground": r.operator,
    "symbolIcon.packageForeground": r.type,
    "symbolIcon.propertyForeground": r.text,
    "symbolIcon.referenceForeground": r.variable,
    "symbolIcon.snippetForeground": fg.muted,
    "symbolIcon.stringForeground": r.string,
    "symbolIcon.structForeground": r.type,
    "symbolIcon.textForeground": fg.muted,
    "symbolIcon.typeParameterForeground": r.type,
    "symbolIcon.unitForeground": r.constant,
    "symbolIcon.variableForeground": r.variable,

    // Notebook
    "notebook.cellBorderColor": bg.line,
    "notebook.focusedCellBorder": a.focus,
    "notebook.focusedEditorBorder": a.focus,
    "notebook.selectedCellBorder": bg.line,
    "notebook.cellEditorBackground": bg.chrome,

    // Charts, markdown alerts, misc
    "charts.foreground": fg.default,
    "charts.lines": bg.line,
    "charts.red": ink.red,
    "charts.blue": ink.blue,
    "charts.yellow": ink.yellow,
    "charts.orange": ink.orange,
    "charts.green": ink.green,
    "charts.purple": ink.violet,
    "markdownAlert.note.foreground": ink.blue,
    "markdownAlert.tip.foreground": ink.green,
    "markdownAlert.important.foreground": ink.violet,
    "markdownAlert.warning.foreground": ink.yellow,
    "markdownAlert.caution.foreground": ink.red,
    "problemsErrorIcon.foreground": status.error,
    "problemsWarningIcon.foreground": status.warning,
    "problemsInfoIcon.foreground": status.info,
    "ports.iconRunningProcessForeground": status.success,
    "welcomePage.tileBackground": widget,
    "welcomePage.tileHoverBackground": hover(widget),
    "welcomePage.tileBorder": bg.line,
  };
}
